### PR TITLE
Day11 Ex1 NoteSQLite 

### PR DESCRIPTION
**Pull request by anhhuy173**
#### Description (Required)
- [x] Create layout 
- [x] Add note model
- [x] Add SQLite
#### Reference (Optional)

### CODE REVIEW

**Comment by at-tamnguyen2** [comment]
@anhhuy173 
LGTM
Thanks you

**Comment by anhhuy173** [comment]
Thanks @at-tamnguyen2 reviewed for me 👍

**Comment by at-tienhoang** [comment]
@anhhuy173 Please resolve conflict

**Comment by anhhuy173** [comment]
Thank you @at-tienhoang 👍 
I fixed this conflict.

**Comment by at-tienhoang** [comment]
@anhhuy173 plz resolve conflict

**Comment by anhhuy173** [comment]
@at-tienhoang I fixed that conflict.

**Pull request merged**
