### PR TITLE
Day15 Ex1 ViewPager, Json, CustomDialogFragment

### PR DESCRIPTION
**Pull request by anhhuy173**
#### Related issues (Optional)
Task #70
#### Description (Required)
- [x] Create Test Activity with ViewPager and Result Activity with RecyclerView
- [x] Add Question model
- [x] Read JSON from assets
- [x] Parse JSON to model
- [x] Compare and calculate number of correct answer
#### Reference (Optional)

### CODE REVIEW

**Comment by at-tamnguyen2** [comment]
@anhhuy173 
LGTM
Thank you

**Comment by anhhuy173** [comment]
Thanks @at-tamnguyen2 reviewed for me 👍

**Comment by at-tienhoang** [comment]
@anhhuy173 Please resolve conflict

**Comment by anhhuy173** [comment]
Yes @at-tienhoang i will fix it. Thank you.

**Comment by at-tienhoang** [comment]
@anhhuy173 Please resolve conflict

**Comment by anhhuy173** [comment]
Thank yo @at-tienhoang 👍 
I fixed this conflict.

**Comment by at-tienhoang** [comment]
LGTM, thanks

**Pull request merged**
